//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class ContactSentDetail
{
    public string senderName { get; set; }
    public string emailAddress { get; set; }
    public string companyName { get; set; }
    public string subjectField { get; set; }
    public string messageField { get; set; }
    public Nullable<System.DateTime> dateRecieved { get; set; }
}
