//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Data.Entity.Core.Objects;
using System.Linq;

public partial class TestSiteDBEntities : DbContext
{
    public TestSiteDBEntities()
        : base("name=TestSiteDBEntities")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public virtual DbSet<ContactSentDetail> ContactSentDetails1 { get; set; }

    public virtual int Insert_Message(string senderName, string emailAddress, string companyName, string subjectField, string messageField)
    {
        var senderNameParameter = senderName != null ?
            new ObjectParameter("senderName", senderName) :
            new ObjectParameter("senderName", typeof(string));

        var emailAddressParameter = emailAddress != null ?
            new ObjectParameter("emailAddress", emailAddress) :
            new ObjectParameter("emailAddress", typeof(string));

        var companyNameParameter = companyName != null ?
            new ObjectParameter("companyName", companyName) :
            new ObjectParameter("companyName", typeof(string));

        var subjectFieldParameter = subjectField != null ?
            new ObjectParameter("subjectField", subjectField) :
            new ObjectParameter("subjectField", typeof(string));

        var messageFieldParameter = messageField != null ?
            new ObjectParameter("messageField", messageField) :
            new ObjectParameter("messageField", typeof(string));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Insert_Message", senderNameParameter, emailAddressParameter, companyNameParameter, subjectFieldParameter, messageFieldParameter);
    }
}
